### ISSUE TITLE
funky dashboard behavior

### ISSUE THREAD

**Issue by tyarrow1** [discobots2587/2018-PowerUp#6]
If the autonType chooser is changed, the autonChooser choice does not visually update (even though it should be impossible to choose that option). However, the chooser itself updates immediately.

Additionally, if an option isn't chosen to overwrite this "phantom option", then the getSelected() of the chooser returns null instead of the default option that it normally would (in this case "Nothing").

**Comment by alexling540** [comment]
Fixed with internal chooser
